### PR TITLE
:hammer: fallback to Foundry remappings

### PR DESCRIPTION
**Pull request by GianfrancoBazzani**
Hey guys i had a problem with resolution when not all remappings are defined in remmapings.txt

### CODE REVIEW

**Comment by GianfrancoBazzani** [comment]
Hi @0xalpharush not sure how to do that, seems that `find_remappings` is performing some extra checks.

**Review by tuturu-tech — CHANGES_REQUESTED** [review]
- Update the PR so that the crytic-compile platform config remappings are used
- Run the subprocess before fetching the remappings file and merge the two (without duplicates)
- Add a single test case for when the remappings file does not contain all of the remappings

**Comment by tuturu-tech** [comment]
I'll be updating the PR with the proposed changes sometime this week so we can merge it. @GianfrancoBazzani really appreciate you opening the PR and highlighting the issue

**Comment by GianfrancoBazzani** [comment]
Thank you, I don't had time to check it out :(.

**Review by tuturu-tech — APPROVED** [review]

**Pull request merged**
